import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWrap from "./LayoutWrap";
import { ToastContainer } from "react-toastify";
import { Provider } from "react-redux";
// import { store } from "./Store/Store";
// import { AuthProvider } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
      >
        {/* <AuthProvider> */}
        <LayoutWrap>
          
          <ToastContainer />
          {/* <LayoutWrap> */}
            {children}
          {/* </LayoutWrap> */}
        </LayoutWrap>
        {/* </AuthProvider> */}
        {/* <LayoutWrap>
          
          <ToastContainer />
            {children}
        </LayoutWrap> */}



      </body>
    </html>
  );
}
